# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DiamondMakeDB.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormDiamondMakeDB(object):
    def setupUi(self, FormDiamondMakeDB):
        FormDiamondMakeDB.setObjectName("FormDiamondMakeDB")
        FormDiamondMakeDB.resize(469, 356)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(FormDiamondMakeDB)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_file = QtWidgets.QLabel(FormDiamondMakeDB)
        self.label_file.setObjectName("label_file")
        self.horizontalLayout_2.addWidget(self.label_file)
        self.lineEdit_input = QtWidgets.QLineEdit(FormDiamondMakeDB)
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.horizontalLayout_2.addWidget(self.lineEdit_input)
        self.toolButton_input = QtWidgets.QToolButton(FormDiamondMakeDB)
        self.toolButton_input.setObjectName("toolButton_input")
        self.horizontalLayout_2.addWidget(self.toolButton_input)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_outfile = QtWidgets.QLabel(FormDiamondMakeDB)
        self.label_outfile.setObjectName("label_outfile")
        self.horizontalLayout_3.addWidget(self.label_outfile)
        self.lineEdit_out = QtWidgets.QLineEdit(FormDiamondMakeDB)
        self.lineEdit_out.setObjectName("lineEdit_out")
        self.horizontalLayout_3.addWidget(self.lineEdit_out)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.plainTextEdit_out = QtWidgets.QPlainTextEdit(FormDiamondMakeDB)
        self.plainTextEdit_out.setObjectName("plainTextEdit_out")
        self.verticalLayout.addWidget(self.plainTextEdit_out)
        self.pushButton_build = QtWidgets.QPushButton(FormDiamondMakeDB)
        self.pushButton_build.setObjectName("pushButton_build")
        self.verticalLayout.addWidget(self.pushButton_build)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(FormDiamondMakeDB)
        QtCore.QMetaObject.connectSlotsByName(FormDiamondMakeDB)

    def retranslateUi(self, FormDiamondMakeDB):
        _translate = QtCore.QCoreApplication.translate
        FormDiamondMakeDB.setWindowTitle(_translate("FormDiamondMakeDB", "DiamondMakeDB"))
        self.label_file.setText(_translate("FormDiamondMakeDB", "Input file:"))
        self.toolButton_input.setText(_translate("FormDiamondMakeDB", "..."))
        self.label_outfile.setText(_translate("FormDiamondMakeDB", "DB name:"))
        self.pushButton_build.setText(_translate("FormDiamondMakeDB", "Build"))
