# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(865, 618)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(10, 10, 100, 391))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setMaximumSize(QtCore.QSize(500, 16777215))
        self.treeView.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.treeView.setObjectName("treeView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 865, 22))
        self.menubar.setObjectName("menubar")
        self.menuLocal_BLAST = QtWidgets.QMenu(self.menubar)
        self.menuLocal_BLAST.setObjectName("menuLocal_BLAST")
        self.menuTranslate_tool = QtWidgets.QMenu(self.menubar)
        self.menuTranslate_tool.setObjectName("menuTranslate_tool")
        self.menuNCBI_Entry = QtWidgets.QMenu(self.menubar)
        self.menuNCBI_Entry.setObjectName("menuNCBI_Entry")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_makeblastdb = QtWidgets.QAction(MainWindow)
        self.action_makeblastdb.setObjectName("action_makeblastdb")
        self.actionBlast = QtWidgets.QAction(MainWindow)
        self.actionBlast.setObjectName("actionBlast")
        self.action_Blastdbcmd = QtWidgets.QAction(MainWindow)
        self.action_Blastdbcmd.setObjectName("action_Blastdbcmd")
        self.actionTranslate_tool = QtWidgets.QAction(MainWindow)
        self.actionTranslate_tool.setObjectName("actionTranslate_tool")
        self.actionEntry = QtWidgets.QAction(MainWindow)
        self.actionEntry.setObjectName("actionEntry")
        self.actionDiamond = QtWidgets.QAction(MainWindow)
        self.actionDiamond.setObjectName("actionDiamond")
        self.menuLocal_BLAST.addAction(self.action_makeblastdb)
        self.menuLocal_BLAST.addAction(self.actionBlast)
        self.menuLocal_BLAST.addAction(self.action_Blastdbcmd)
        self.menuLocal_BLAST.addSeparator()
        self.menuLocal_BLAST.addAction(self.actionDiamond)
        self.menuTranslate_tool.addAction(self.actionTranslate_tool)
        self.menuNCBI_Entry.addAction(self.actionEntry)
        self.menubar.addAction(self.menuLocal_BLAST.menuAction())
        self.menubar.addAction(self.menuTranslate_tool.menuAction())
        self.menubar.addAction(self.menuNCBI_Entry.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuLocal_BLAST.setTitle(_translate("MainWindow", "BLAST"))
        self.menuTranslate_tool.setTitle(_translate("MainWindow", "Translate tool"))
        self.menuNCBI_Entry.setTitle(_translate("MainWindow", "NCBI Entry"))
        self.action_makeblastdb.setText(_translate("MainWindow", "Makeblastdb"))
        self.actionBlast.setText(_translate("MainWindow", "Blast"))
        self.action_Blastdbcmd.setText(_translate("MainWindow", "Blastdbcmd"))
        self.actionTranslate_tool.setText(_translate("MainWindow", "Translate_tool"))
        self.actionEntry.setText(_translate("MainWindow", "NCBI Entry"))
        self.actionDiamond.setText(_translate("MainWindow", "Diamond"))
