# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'blast_out.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BLASTOUT(object):
    def setupUi(self, BLASTOUT):
        BLASTOUT.setObjectName("BLASTOUT")
        BLASTOUT.resize(999, 574)
        self.verticalLayout = QtWidgets.QVBoxLayout(BLASTOUT)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(BLASTOUT)
        self.plainTextEdit.setEnabled(True)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_2.addWidget(self.plainTextEdit)
        self.plainTextEdit_blastdbcmd = QtWidgets.QPlainTextEdit(BLASTOUT)
        self.plainTextEdit_blastdbcmd.setEnabled(True)
        self.plainTextEdit_blastdbcmd.setPlainText("")
        self.plainTextEdit_blastdbcmd.setObjectName("plainTextEdit_blastdbcmd")
        self.horizontalLayout_2.addWidget(self.plainTextEdit_blastdbcmd)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_db = QtWidgets.QLabel(BLASTOUT)
        self.label_db.setObjectName("label_db")
        self.horizontalLayout.addWidget(self.label_db)
        self.lineEdit_db = QtWidgets.QLineEdit(BLASTOUT)
        self.lineEdit_db.setText("")
        self.lineEdit_db.setObjectName("lineEdit_db")
        self.horizontalLayout.addWidget(self.lineEdit_db)
        self.label_entry = QtWidgets.QLabel(BLASTOUT)
        self.label_entry.setObjectName("label_entry")
        self.horizontalLayout.addWidget(self.label_entry)
        self.lineEdit_entry = QtWidgets.QLineEdit(BLASTOUT)
        self.lineEdit_entry.setText("")
        self.lineEdit_entry.setObjectName("lineEdit_entry")
        self.horizontalLayout.addWidget(self.lineEdit_entry)
        self.label = QtWidgets.QLabel(BLASTOUT)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_range = QtWidgets.QLineEdit(BLASTOUT)
        self.lineEdit_range.setInputMask("")
        self.lineEdit_range.setObjectName("lineEdit_range")
        self.horizontalLayout.addWidget(self.lineEdit_range)
        self.pushButton_blastdbcmd = QtWidgets.QPushButton(BLASTOUT)
        self.pushButton_blastdbcmd.setObjectName("pushButton_blastdbcmd")
        self.horizontalLayout.addWidget(self.pushButton_blastdbcmd)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_save = QtWidgets.QPushButton(BLASTOUT)
        self.pushButton_save.setEnabled(True)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout.addWidget(self.pushButton_save)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(BLASTOUT)
        QtCore.QMetaObject.connectSlotsByName(BLASTOUT)

    def retranslateUi(self, BLASTOUT):
        _translate = QtCore.QCoreApplication.translate
        BLASTOUT.setWindowTitle(_translate("BLASTOUT", "BLASTOUT"))
        self.label_db.setText(_translate("BLASTOUT", "db:"))
        self.label_entry.setText(_translate("BLASTOUT", "entry:"))
        self.label.setText(_translate("BLASTOUT", "range"))
        self.lineEdit_range.setText(_translate("BLASTOUT", "1-100"))
        self.pushButton_blastdbcmd.setText(_translate("BLASTOUT", "blastdbcmd"))
        self.pushButton_save.setText(_translate("BLASTOUT", "Save"))
