# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_blast_make_db.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_make_db(object):
    def setupUi(self, Form_make_db):
        Form_make_db.setObjectName("Form_make_db")
        Form_make_db.resize(420, 271)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form_make_db)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_file = QtWidgets.QLabel(Form_make_db)
        self.label_file.setObjectName("label_file")
        self.horizontalLayout_2.addWidget(self.label_file)
        self.lineEdit_input = QtWidgets.QLineEdit(Form_make_db)
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.horizontalLayout_2.addWidget(self.lineEdit_input)
        self.toolButton_input = QtWidgets.QToolButton(Form_make_db)
        self.toolButton_input.setObjectName("toolButton_input")
        self.horizontalLayout_2.addWidget(self.toolButton_input)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_dbtype = QtWidgets.QLabel(Form_make_db)
        self.label_dbtype.setObjectName("label_dbtype")
        self.horizontalLayout.addWidget(self.label_dbtype)
        self.comboBox = QtWidgets.QComboBox(Form_make_db)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_outfile = QtWidgets.QLabel(Form_make_db)
        self.label_outfile.setObjectName("label_outfile")
        self.horizontalLayout_3.addWidget(self.label_outfile)
        self.lineEdit_out = QtWidgets.QLineEdit(Form_make_db)
        self.lineEdit_out.setObjectName("lineEdit_out")
        self.horizontalLayout_3.addWidget(self.lineEdit_out)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.plainTextEdit_out = QtWidgets.QPlainTextEdit(Form_make_db)
        self.plainTextEdit_out.setObjectName("plainTextEdit_out")
        self.verticalLayout.addWidget(self.plainTextEdit_out)
        self.pushButton_build = QtWidgets.QPushButton(Form_make_db)
        self.pushButton_build.setObjectName("pushButton_build")
        self.verticalLayout.addWidget(self.pushButton_build)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form_make_db)
        QtCore.QMetaObject.connectSlotsByName(Form_make_db)

    def retranslateUi(self, Form_make_db):
        _translate = QtCore.QCoreApplication.translate
        Form_make_db.setWindowTitle(_translate("Form_make_db", "MakeBlastDB"))
        self.label_file.setText(_translate("Form_make_db", "Input file:"))
        self.toolButton_input.setText(_translate("Form_make_db", "..."))
        self.label_dbtype.setText(_translate("Form_make_db", "Database type:"))
        self.comboBox.setItemText(0, _translate("Form_make_db", "nucl"))
        self.comboBox.setItemText(1, _translate("Form_make_db", "prot"))
        self.label_outfile.setText(_translate("Form_make_db", "db name:"))
        self.pushButton_build.setText(_translate("Form_make_db", "Build"))
